
function ExceptionThrower() {
    throw new Error('Catch!');
}
